# Generated by Django 5.0.4 on 2024-04-05 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_blogmodel_sulg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='sulg',
            new_name='slug',
        ),
    ]
