# Generated by Django 5.0.4 on 2024-04-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_sulg_blogmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='userid',
            field=models.CharField(default='dev', max_length=100),
            preserve_default=False,
        ),
    ]
